default_stages: [commit, push]

repos:
  - repo: git@github.com:Yelp/detect-secrets
    rev: v1.2.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: [--branch, develop, --branch, master, --branch, main, --pattern, release/.*]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
