name: Build and Push Jupyter-rcc image

on:
  push:
    paths:
    - jupyter-rcc/**
    - .github/workflows/build_jupyter_rcc_image.yml

jobs:
  jupyter-midrc-bih:
    name: Build and Push jupyter-rcc image
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./jupyter-rcc/Dockerfile"
      DOCKERFILE_BUILD_CONTEXT: "./jupyter-rcc"
      OVERRIDE_REPO_NAME: "jupyter-notebook"
      OVERRIDE_TAG_NAME: "rcc-$(echo ${GITHUB_REF#refs/*/} | tr / _)"
      BUILD_PLATFORMS: "linux/amd64"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
