name: Push new nextflow images to ECR
on:
  workflow_dispatch:
  push:
    # branches: master
    paths:
      - 'nextflow-base-images/**' #Runs every time this folder gets updated
      - '.github/workflows/feat/automate_nf_base_images_build'
  schedule:
    - cron: '0 0 * * 6'  # Run at midnight UTC every Saturday

jobs:
  get_image_layers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout other private repository
        uses: actions/checkout@v3
        with:
          repository: uc-cdis/base-images # Replace with your organization and repo
          token: ${{ secrets.PLANXCYBORG_TOKEN }}       # Use the secret created earlier
          path: base-images                          # Specify a path to checkout the repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Amazon ECR
        env:
          AWS_REGION: us-east-1  # Replace with your AWS region
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ACCT_654654631253_ECR }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ACCT_654654631253_ECR }}
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin 143731057154.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker images
        run: |
              dir=base-images/amazonlinux-base/
              image_name=nextflow-approved/public
              tag_name=$(basename "$dir")
              echo "$image_name:$tag_name"
              # docker build -t public.ecr.aws/u5x5h6w3/$image_name:$tag_name $dir
              # docker push public.ecr.aws/u5x5h6w3/$image_name:$tag_name
              docker build -t 143731057154.dkr.ecr.us-east-1.amazonaws.com/nextflow-staging/test:$tag_name $dir
              docker push 143731057154.dkr.ecr.us-east-1.amazonaws.com/nextflow-staging/test:$tag_name

              for dir in nextflow-base-images/*/;do
                  image_name=nextflow-approved/public
                  tag_name=$(basename "$dir" | sed 's/_/./g')
                  # docker build -t public.ecr.aws/u5x5h6w3/$image_name:$tag_name $dir
                  # docker push public.ecr.aws/u5x5h6w3/$image_name:$tag_name
                  docker build -t 143731057154.dkr.ecr.us-east-1.amazonaws.com/nextflow-staging/test:$tag_name $dir
                  docker push 143731057154.dkr.ecr.us-east-1.amazonaws.com/nextflow-staging/test:$tag_name
                  echo "$image_name:$tag_name"
                  echo $dir
              done
