name: Build and Push python3.9-data-science

on:
  push:
    paths:
    - python3.9-data-science/**
    - .github/workflows/build_and_push_python_image.yml

jobs:
  python_3-9:
    name: Build and Push python3.9-data-science
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./python3.9-data-science/Dockerfile"
      DOCKERFILE_BUILD_CONTEXT: "./python3.9-data-science"
      OVERRIDE_REPO_NAME: "python"
      OVERRIDE_TAG_NAME: "python3.9-data-science-$(echo ${GITHUB_REF#refs/*/} | tr / _)"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
