name: Update Nextflow-approved image's layers
on:
  push:
    # branches: master
    paths:
      - 'nextflow-base-images/**' #Runs every time this folder gets updated
      - '.github/workflows/get_layer_info_for_nf_imgs.yml'
  schedule:
    - cron: '0 0 * * 6'  # Run at midnight UTC every Saturday

jobs:
  get_image_layers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Checkout other private repository
        uses: actions/checkout@v3
        with:
          repository: uc-cdis/base-images # Replace with your organization and repo
          token: ${{ secrets.PLANXCYBORG_TOKEN }}       # Use the secret created earlier
          path: base-images                          # Specify a path to checkout the repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to Amazon ECR
      #   env:
      #     AWS_REGION: us-west-1  # Replace with your AWS region
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   run: |
      #     aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws/u5x5h6w3

      - name: Build and push Docker images
        run: |
              dir=base-images/amazonlinux-base/
              image_name=nextflow-approved/public
              tag_name=$(basename "$dir" | sed 's/_/./g')
              echo "$image_name:$tag_name"
              # docker build -t public.ecr.aws/u5x5h6w3/$image_name:$tag_name $dir
              # docker push public.ecr.aws/u5x5h6w3/$image_name:$tag_name

              for dir in nextflow-base-images/*/;do
                  image_name=nextflow-approved/public
                  tag_name=$(basename "$dir" | sed 's/_/./g')
                  # docker build -t public.ecr.aws/u5x5h6w3/$image_name:$tag_name $dir
                  # docker push public.ecr.aws/u5x5h6w3/$image_name:$tag_name
                  echo "$image_name:$tag_name"
                  echo $dir
              done
