name: Push Stata User-licensed Image to quay

on:
  push:
    paths:
      - jupyter-pystata-user-licensed/**
      - .github/workflows/build_push_stata_user_licensed.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
      - uses: actions/checkout@v4
      - uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: 's3://ctds-stata/Stata17Linux64.tar.gz'
          dest: './jupyter-pystata-user-licensed/resources/'

      - name: Extract branch name
        id: extract_branch
        run: |
          echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/*/} | tr / _)"
          echo "IMAGE_TAG=$(echo ${GITHUB_REF#refs/*/} | tr / _)" >> $GITHUB_ENV

      - name: Login to Quay.io
        id: login
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            quay.io/cdis/jupyter-pystata-user-licensed:${{ env.IMAGE_TAG }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: ./jupyter-pystata-user-licensed"
          file: "./jupyter-pystata-user-licensed/Dockerfile"
          push: true
          tags: |
            quay.io/cdis/jupyter-pystata-user-licensed:${{ env.IMAGE_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: "linux/amd64, linux/arm64"
