name: Build and Push jupyter-covid19

on:
  push:
    paths:
    - jupyter-covid19/**
    - .github/workflows/build_jupyter_covid19_image.yml

jobs:
  jupyter-covid19:
    name: Build and Push jupyter-covid19
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./jupyter-covid19/Dockerfile"
      DOCKERFILE_BUILD_CONTEXT: "./jupyter-covid19"
      OVERRIDE_REPO_NAME: "jupyter-notebook"
      OVERRIDE_TAG_NAME: "covid19-$(echo ${GITHUB_REF#refs/*/} | tr / _)"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
