name: Push Stata User-licensed Image to quay

on:
  push:
    paths:
      - jupyter-pystata-user-licensed/**
      - .github/workflows/build_push_stata_user_licensed.yml
  workflow_dispatch:

jobs:
  stata_user-licensed:
    name: Build and Push user licensed Stata workspace image
    uses: uc-cdis/.github/.github/workflows/image_build_push.yaml@master
    with:
      DOCKERFILE_LOCATION: "./jupyter-pystata-user-licensed/Dockerfile"
      DOCKERFILE_BUILD_CONTEXT: "./jupyter-pystata-user-licensed"
      OVERRIDE_REPO_NAME: "jupyter-pystata-user-licensed"
      OVERRIDE_TAG_NAME: "jupyter-pystata-user-licensed-$(echo ${GITHUB_REF#refs/*/} | tr / _)"
    secrets:
      ECR_AWS_ACCESS_KEY_ID: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
      ECR_AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_ROBOT_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
